<a href="https://colab.research.google.com/github/ESSPRADEEP3000/AI_intership/blob/main/task8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
#task-6 ->Calculating the average duration of each customer.
import pandas as pd
customers_df=pd.read_csv('/content/drive/MyDrive/internship/Customers.csv')
transaction_df=pd.read_csv('/content/drive/MyDrive/internship/Transaction.csv')
continent_df=pd.read_csv('/content/drive/MyDrive/internship/Continent.csv')
merged_df=pd.merge(customers_df,transaction_df,on="customer_id")
merged_df2=pd.merge(merged_df,continent_df,on="region_id")
merged_df2['start_date']= pd.to_datetime(merged_df2['start_date'],format="%d-%m-%Y")
#some end dates are causing out of bound errors to deal with we find such dates first
problamatic_dates=merged_df2[merged_df2['end_date']=='31-12-9999']
# print(problamatic_dates)
#now we replace such dates with a text NaT (or) replace with the final date
merged_df2.loc[merged_df2['end_date']=='31-12-9999','end_date']=pd.NaT
merged_df2['end_date']= pd.to_datetime(merged_df2['end_date'],format="%d-%m-%Y")
# Timedelta object representing the time difference.
# .dt.days accesses the days attribute of the Timedelta object, returning the duration in days.
merged_df2['duration']=(merged_df2['end_date']-merged_df2['start_date']).dt.days
merged_df2

,customer_id,region_id,start_date,end_date,txn_date,txn_type,txn_amount,region_name,duration
0,1,3,2020-01-02,2020-01-03,02-01-2020,deposit,312,Africa,1.0
1,1,3,2020-01-02,2020-01-03,05-03-2020,purchase,612,Africa,1.0
2,1,3,2020-01-02,2020-01-03,17-03-2020,deposit,324,Africa,1.0
3,1,3,2020-01-02,2020-01-03,19-03-2020,purchase,664,Africa,1.0
4,1,3,2020-01-04,2020-01-14,02-01-2020,deposit,312,Africa,10.0
...,...,...,...,...,...,...,...,...,...
41071,493,4,2020-03-19,NaT,07-04-2020,deposit,918,Asia,NaN
41072,493,4,2020-03-19,NaT,29-02-2020,withdrawal,465,Asia,NaN
41073,493,4,2020-03-19,NaT,14-02-2020,deposit,173,Asia,NaN
41074,493,4,2020-03-19,NaT,12-04-2020,withdrawal,832,Asia,NaN
41075,493,4,2020-03-19,NaT,14-02-2020,withdrawal,483,Asia,NaN

In [4]:
merged_df2.drop_duplicates(inplace=True)
merged_df2.dropna(inplace=True)
merged_df2

,customer_id,region_id,start_date,end_date,txn_date,txn_type,txn_amount,duration
0,1,3,2020-01-02,2020-01-03,02-01-2020,deposit,312,1.0
1,1,3,2020-01-02,2020-01-03,05-03-2020,purchase,612,1.0
2,1,3,2020-01-02,2020-01-03,17-03-2020,deposit,324,1.0
3,1,3,2020-01-02,2020-01-03,19-03-2020,purchase,664,1.0
4,1,3,2020-01-04,2020-01-14,02-01-2020,deposit,312,10.0
...,...,...,...,...,...,...,...,...
41055,500,2,2020-03-19,2020-04-14,27-01-2020,deposit,214,26.0
41056,500,2,2020-03-19,2020-04-14,01-03-2020,purchase,929,26.0
41057,500,2,2020-03-19,2020-04-14,30-01-2020,deposit,922,26.0
41058,500,2,2020-03-19,2020-04-14,18-01-2020,deposit,308,26.0
41059,500,2,2020-03-19,2020-04-14,11-03-2020,purchase,426,26.0

In [21]:
merged_df2['average_duration']=merged_df2.groupby('customer_id')['duration'].mean().round(2)
merged_df2

,customer_id,region_id,start_date,end_date,txn_date,txn_type,txn_amount,region_name,duration,average_duration
0,1,3,2020-01-02,2020-01-03,02-01-2020,deposit,312,Africa,1.0,NaN
1,1,3,2020-01-02,2020-01-03,05-03-2020,purchase,612,Africa,1.0,11.50
2,1,3,2020-01-02,2020-01-03,17-03-2020,deposit,324,Africa,1.0,10.83
3,1,3,2020-01-02,2020-01-03,19-03-2020,purchase,664,Africa,1.0,13.83
4,1,3,2020-01-04,2020-01-14,02-01-2020,deposit,312,Africa,10.0,13.33
...,...,...,...,...,...,...,...,...,...,...
41071,493,4,2020-03-19,NaT,07-04-2020,deposit,918,Asia,NaN,NaN
41072,493,4,2020-03-19,NaT,29-02-2020,withdrawal,465,Asia,NaN,NaN
41073,493,4,2020-03-19,NaT,14-02-2020,deposit,173,Asia,NaN,NaN
41074,493,4,2020-03-19,NaT,12-04-2020,withdrawal,832,Asia,NaN,NaN
41075,493,4,2020-03-19,NaT,14-02-2020,withdrawal,483,Asia,NaN,NaN

In [12]:
uni_txn_types=merged_df2['txn_type'].unique()
print(uni_txn_types)

['deposit' 'purchase' 'withdrawal']

In [22]:
count_txn_type_continent=merged_df2.groupby(['txn_type','region_name']).size()
print(count_txn_type_continent)

txn_type    region_name
deposit     Africa         3759
            America        4060
            Asia           3682
            Australia      4053
            Europe         3143
purchase    Africa         2338
            America        2359
            Asia           2149
            Australia      2660
            Europe         1813
withdrawal  Africa         2317
            America        2387
            Asia           2121
            Australia      2394
            Europe         1841
dtype: int64